const drawBtn=document.getElementById('drawBtn'),resetBtn=document.getElementById('resetBtn'),numberRow=document.getElementById('numberRow'),drawState=document.getElementById('drawState'),historyGrid=document.getElementById('historyGrid'),soundBtn=document.getElementById('soundBtn');
let soundOn=true,drawing=false,selected=[];
function uniqueNumbers(){const a=Array.from({length:45},(_,i)=>i+1);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,6)}
function colorClass(n){return n<=10?'yellow':n<=20?'blue':n<=30?'red':n<=40?'gray':'green'}
function beep(freq=520,duration=.07){if(!soundOn)return;try{const ac=beep.ac||(beep.ac=new AudioContext()),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.04,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+duration)}catch(e){}}
async function draw(){
  if(drawing||!window.extractLottoBall)return;drawing=true;drawBtn.disabled=true;window.setResultStageLowered?.(false);selected=uniqueNumbers();drawState.textContent='공을 강하게 혼합하고 있어요…';numberRow.innerHTML=Array(6).fill('<span class="number empty">?</span>').join('');window.setLottoSpinning(true);beep(180,.2);await new Promise(r=>setTimeout(r,1900));
  for(let i=0;i<selected.length;i++){const n=selected[i];drawState.textContent=`${i+1}번째 공 배출 중…`;await window.extractLottoBall(n,i);numberRow.children[i].outerHTML=`<span class="number landed ${colorClass(n)}">${n}</span>`;beep(390+n*9,.1);await new Promise(r=>setTimeout(r,240))}
  window.setLottoSpinning(false);window.setResultStageLowered?.(true);drawing=false;drawBtn.disabled=false;drawState.textContent='6개의 행운 공 추첨 완료';saveHistory(selected);renderHistory();
}
function saveHistory(nums){const list=JSON.parse(localStorage.getItem('lucky-orbit-history')||'[]');list.unshift({nums,date:new Date().toISOString()});localStorage.setItem('lucky-orbit-history',JSON.stringify(list.slice(0,6)))}
function renderHistory(){const list=JSON.parse(localStorage.getItem('lucky-orbit-history')||'[]');if(!list.length){historyGrid.innerHTML='<div class="empty-history"><span>✦</span><p>아직 추첨 기록이 없어요.<br>첫 번째 행운을 만들어 보세요.</p></div>';return}historyGrid.innerHTML=list.map((x,i)=>`<article class="history-card"><div class="history-card-head"><span>정렬된 번호</span><time>${new Date(x.date).toLocaleString('ko-KR',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></div><div class="mini-numbers">${[...x.nums].sort((a,b)=>a-b).map(n=>`<i class="${colorClass(n)}">${n}</i>`).join('')}</div></article>`).join('')}
drawBtn.addEventListener('click',draw);resetBtn.addEventListener('click',()=>{if(drawing)return;selected=[];numberRow.innerHTML=Array(6).fill('<span class="number empty">?</span>').join('');drawState.textContent='추첨 준비 완료'});soundBtn.addEventListener('click',()=>{soundOn=!soundOn;soundBtn.setAttribute('aria-pressed',soundOn);soundBtn.querySelector('.sound-label').textContent=soundOn?'SOUND ON':'SOUND OFF';soundBtn.querySelector('.sound-icon').textContent=soundOn?'◖))':'◖×'});document.getElementById('clearHistory').addEventListener('click',()=>{localStorage.removeItem('lucky-orbit-history');renderHistory()});const machineActions=document.querySelector('.machine-actions'),machineWrap=document.querySelector('.machine-wrap');new IntersectionObserver(([entry])=>machineActions.classList.toggle('is-docked',!entry.isIntersecting),{threshold:.18}).observe(machineWrap);function keepResultsInFront(){window.__lottoBalls?.forEach(ball=>{if(ball.userData.collected){ball.material.transparent=true;ball.material.opacity=1;ball.material.depthTest=false;ball.material.depthWrite=false;ball.renderOrder=1000;ball.children.forEach(label=>{label.material.depthTest=false;label.material.depthWrite=false;label.renderOrder=1001})}});requestAnimationFrame(keepResultsInFront)}keepResultsInFront();renderHistory();
