const THREE=window.THREE,host=document.getElementById('threeMachine');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(1.65,-.05,17.2);camera.lookAt(0,-.15,0);
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xcaffdc,0x020805,2.3));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(-5,7,8);scene.add(key);const greenLight=new THREE.PointLight(0x19e879,18,16);greenLight.position.set(4,-1,4);scene.add(greenLight);
const machine=new THREE.Group();machine.position.y=.9;scene.add(machine);const metal=new THREE.MeshStandardMaterial({color:0x617469,metalness:.94,roughness:.2}),dark=new THREE.MeshStandardMaterial({color:0x101c15,metalness:.88,roughness:.3}),glass=new THREE.MeshPhysicalMaterial({color:0xcaffdc,transmission:.96,transparent:true,opacity:.25,roughness:.04,thickness:.2,ior:1.47,clearcoat:1,side:THREE.DoubleSide,depthWrite:false});
const shell=new THREE.Mesh(new THREE.SphereGeometry(3.5,64,48),glass);shell.renderOrder=5;machine.add(shell);const rim=new THREE.Mesh(new THREE.TorusGeometry(3.55,.12,18,96),metal);machine.add(rim);const rearRim=rim.clone();rearRim.rotation.y=Math.PI/2;rearRim.material=dark;machine.add(rearRim);
for(let a=0;a<Math.PI*2;a+=Math.PI/4){const bolt=new THREE.Mesh(new THREE.SphereGeometry(.09,16,10),metal);bolt.position.set(Math.cos(a)*3.55,Math.sin(a)*3.55,.13);machine.add(bolt)}
const axle=new THREE.Mesh(new THREE.CylinderGeometry(.25,.25,7.5,24),dark);axle.rotation.z=Math.PI/2;machine.add(axle);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.56,.56,.3,32),metal);hub.rotation.x=Math.PI/2;hub.position.z=.18;machine.add(hub);const paddles=new THREE.Group();machine.add(paddles);for(let i=0;i<3;i++){const p=new THREE.Mesh(new THREE.BoxGeometry(5.4,.1,.2),dark);p.rotation.z=i*Math.PI/3;paddles.add(p)}
const colors=[0xf3d635,0x41a5f5,0xef5a46,0xd8dfd9,0x38d47b],cssColors=['#f3d635','#41a5f5','#ef5a46','#d8dfd9','#38d47b'],balls=new Map();window.__lottoBalls=balls;
function texture(n){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='#fff';x.beginPath();x.arc(64,64,38,0,Math.PI*2);x.fill();x.fillStyle='#102017';x.font='bold 42px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(n,64,67);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
for(let n=1;n<=45;n++){const b=new THREE.Mesh(new THREE.SphereGeometry(.27,32,24),new THREE.MeshPhysicalMaterial({color:colors[Math.floor((n-1)/10)],roughness:.18,clearcoat:1}));const r=2.75*Math.cbrt(Math.random()),th=Math.random()*6.28,ph=Math.acos(2*Math.random()-1);b.position.set(r*Math.sin(ph)*Math.cos(th),r*Math.sin(ph)*Math.sin(th),r*Math.cos(ph));b.userData={v:new THREE.Vector3((Math.random()-.5)*.04,(Math.random()-.5)*.04,(Math.random()-.5)*.04),number:n};const labelMat=new THREE.MeshBasicMaterial({map:texture(n),transparent:true,polygonOffset:true,polygonOffsetFactor:-2}),geo=new THREE.CircleGeometry(.16,24);[[0,0,.269,0,0,0],[0,0,-.269,0,Math.PI,0],[.269,0,0,0,Math.PI/2,0],[-.269,0,0,0,-Math.PI/2,0],[0,.269,0,-Math.PI/2,0,0],[0,-.269,0,Math.PI/2,0,0]].forEach(v=>{const label=new THREE.Mesh(geo,labelMat);label.position.set(v[0],v[1],v[2]);label.rotation.set(v[3],v[4],v[5]);b.add(label)});machine.add(b);balls.set(n,b)}
const neck=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.35,1.2,32),dark);neck.position.y=-4.05;machine.add(neck);
// 방송 추첨기처럼 하단 리프트가 공을 상단 게이트까지 밀어 올린다.
const lift=new THREE.Group();machine.add(lift);const liftRod=new THREE.Mesh(new THREE.CylinderGeometry(.13,.17,5.8,20),metal);liftRod.position.set(0,-5.8,.35);lift.add(liftRod);const liftCup=new THREE.Mesh(new THREE.CylinderGeometry(.34,.25,.16,24),dark);liftCup.position.set(0,-2.95,.35);lift.add(liftCup);
const gate=new THREE.Mesh(new THREE.TorusGeometry(.43,.11,14,32),metal);gate.position.set(0,3.55,.35);gate.rotation.x=Math.PI/2;machine.add(gate);
// 상단에서 두 바퀴 반을 감아 내려오는 이중 나선 레일.
const spiralPoints=[],helixEntry=new THREE.Vector3(2.7,-3.22,1.25);for(let i=0;i<=140;i++){const p=i/140,a=Math.PI/2-p*Math.PI*5,r=4.0,depth=1.72,point=new THREE.Vector3(Math.cos(a)*r,3.62-p*6.9,.35+Math.sin(a)*depth);if(i>116){const q=THREE.MathUtils.smoothstep((i-116)/24,0,1);point.lerp(helixEntry,q)}spiralPoints.push(point)}const curve=new THREE.CatmullRomCurve3(spiralPoints,false,'centripetal');const railMat=new THREE.MeshStandardMaterial({color:0x91a49a,metalness:.95,roughness:.14});[-.25,.25].forEach(z=>{const railCurve=new THREE.CatmullRomCurve3(spiralPoints.map(p=>p.clone().add(new THREE.Vector3(0,0,z))),false,'centripetal');machine.add(new THREE.Mesh(new THREE.TubeGeometry(railCurve,240,.07,10,false),railMat))});for(let i=0;i<=14;i++){const p=curve.getPoint(i/14),tie=new THREE.Mesh(new THREE.BoxGeometry(.08,.08,.62),dark);tie.position.copy(p);machine.add(tie)}
const trayY=-3.22,trayZ=1.25,trayXs=Array.from({length:6},(_,i)=>-2.25+i*.9),runoutPoints=[curve.getPoint(1)];[-.3,.3].forEach(z=>{const trayCurve=new THREE.LineCurve3(new THREE.Vector3(-2.7,trayY,trayZ+z),new THREE.Vector3(2.7,trayY,trayZ+z));machine.add(new THREE.Mesh(new THREE.TubeGeometry(trayCurve,30,.08,10,false),railMat))});for(const x of [-2.7,...trayXs.map(v=>v+.45)]){const stop=new THREE.Mesh(new THREE.BoxGeometry(.07,.65,.75),dark);stop.position.set(x,trayY-.06,trayZ);machine.add(stop)}
function plateTexture(n,index){const c=document.createElement('canvas');c.width=256;c.height=112;const x=c.getContext('2d');x.fillStyle='#010604';x.beginPath();x.roundRect(4,4,248,104,15);x.fill();x.strokeStyle=n==null?'#175d39':'#35ff91';x.lineWidth=5;x.stroke();x.fillStyle='#659078';x.font='700 13px monospace';x.textAlign='center';x.fillText(`DRAW ${String(index+1).padStart(2,'0')}`,128,20);x.fillStyle=n==null?'#244f38':'#d9ff58';x.shadowColor='#78ff24';x.shadowBlur=n==null?0:5;x.font='900 78px monospace';x.textBaseline='alphabetic';x.fillText(n==null?'--':String(n).padStart(2,'0'),128,102);x.shadowBlur=0;const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.minFilter=THREE.LinearFilter;t.magFilter=THREE.LinearFilter;return t}const plates=trayXs.map((x,i)=>{const s=new THREE.Sprite(new THREE.SpriteMaterial({map:plateTexture(null,i),transparent:true,depthTest:false,depthWrite:false}));s.position.set(x,trayY-.64,trayZ+.35);s.scale.set(1.12,.5,1);s.renderOrder=100;machine.add(s);return s});
let spinning=false,blowerPower=0,extracting=null;window.setLottoSpinning=v=>{spinning=v;if(v){balls.forEach(b=>{if(b.userData.collected){const r=2.4*Math.random(),a=Math.random()*6.28;b.position.set(Math.cos(a)*r,-2+Math.random()*2,Math.sin(a)*r);b.userData.collected=false;b.scale.setScalar(1)}b.material.depthTest=true;b.material.depthWrite=true;b.renderOrder=0;b.children.forEach(label=>label.material.depthTest=true);b.visible=true});plates.forEach((s,i)=>{s.material.map.dispose();s.material.map=plateTexture(null,i);s.material.needsUpdate=true})}};
window.extractLottoBall=(n,index)=>new Promise(resolve=>{const b=balls.get(n),target=new THREE.Vector3(trayXs[index],trayY+.38,trayZ),trayTravel=[],railLift=new THREE.Vector3(0,.3,0);for(let x=2.34;x>trayXs[index]+.05;x-=.36)trayTravel.push(new THREE.Vector3(Math.max(x,trayXs[index]),trayY+.38,trayZ));trayTravel.push(target);const raisedSpiral=spiralPoints.map(p=>p.clone().add(railLift)),raisedRunout=runoutPoints.slice(1).map(p=>p.clone().add(railLift)),railPath=new THREE.CatmullRomCurve3([...raisedSpiral,...raisedRunout,...trayTravel],false,'centripetal');extracting={b,n,index,phase:'lift',liftT:0,railDistance:0,railSpeed:.25,railPath,railLength:railPath.getLength(),resolve,target};balls.forEach(other=>{if(other!==b)other.material.depthWrite=false});b.userData.v.set(0,0,0);b.position.set(0,-2.65,.35);b.scale.setScalar(1);b.material.depthTest=true;b.material.depthWrite=true;b.renderOrder=30;b.children.forEach(label=>{label.material.depthTest=true;label.renderOrder=31});lift.position.y=0});
function flyToResult(n,index,start){return new Promise(resolve=>{const target=document.getElementById('numberRow').children[index].getBoundingClientRect(),el=document.createElement('div');el.className='flying-ball';el.style.setProperty('--ball',cssColors[Math.floor((n-1)/10)]);el.innerHTML=`<b>${n}</b>`;document.body.appendChild(el);const sx=start.x,sy=start.y,ex=target.left+target.width/2,ey=target.top+target.height/2,t0=performance.now();function step(now){const p=Math.min((now-t0)/650,1),e=1-Math.pow(1-p,3),x=sx+(ex-sx)*e,y=sy+(ey-sy)*e-Math.sin(p*Math.PI)*75;el.style.transform=`translate(${x-24}px,${y-24}px) rotate(${p*540}deg) scale(${1-p*.08})`;if(p<1)requestAnimationFrame(step);else{el.remove();resolve()}}requestAnimationFrame(step)})}
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();const clock=new THREE.Clock();
function solveBallCollisions(){const active=[...balls.values()].filter(b=>b.visible&&!b.userData.collected&&extracting?.b!==b),time=performance.now()*.001,nozzle=new THREE.Vector3(0,-3.05,0);if(spinning)active.forEach(b=>{const n=b.userData.number,fromNozzle=b.position.clone().sub(nozzle),distance=fromNozzle.length(),v=b.userData.v;if(distance<2.65&&b.position.y<-.65){const falloff=1-distance/2.65,radial=fromNozzle.normalize();v.addScaledVector(radial,.22*falloff);v.x+=Math.sin(time*17.1+n*2.3)*.08;v.y+=Math.cos(time*15.7+n*.83)*.055;v.z+=Math.sin(time*19.3+n*1.37)*.08}else{v.y-=.105;v.x+=Math.sin(time*13.7+n*1.9)*.045;v.z+=Math.cos(time*14.9+n*1.2)*.045}});for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const a=active[i],b=active[j],delta=b.position.clone().sub(a.position),dist=delta.length(),min=.54;if(dist>0&&dist<min){const normal=delta.multiplyScalar(1/dist),overlap=(min-dist)*.5;a.position.addScaledVector(normal,-overlap);b.position.addScaledVector(normal,overlap);const rel=b.userData.v.clone().sub(a.userData.v),impact=rel.dot(normal);if(impact<0){const impulse=normal.multiplyScalar(impact*.94);a.userData.v.add(impulse);b.userData.v.sub(impulse)}}}}
function animate(){const dt=Math.min(clock.getDelta(),.035),targetPower=spinning?1:0;blowerPower+=(targetPower-blowerPower)*Math.min(dt*(spinning?7.5:2.4),1);const paddleSpeed=.3+blowerPower*6.2,gravity=7.8,airDrag=.28,restitution=.48+blowerPower*.18;paddles.rotation.z+=dt*paddleSpeed;balls.forEach(b=>{if(extracting?.b===b||b.userData.collected)return;const v=b.userData.v,time=performance.now()*.001,n=b.userData.number;if(blowerPower>.015){const jetZone=THREE.MathUtils.clamp((.35-b.position.y)/2.5,0,1),radialFade=THREE.MathUtils.clamp(1-Math.hypot(b.position.x,b.position.z)/3.2,.55,1),jet=jetZone*radialFade;if(jet>.001){v.y+=dt*blowerPower*jet*(88+Math.sin(time*15+n)*14);v.x+=dt*blowerPower*jet*(Math.sin(n*1.73+time*12.4)*27+b.position.z*4);v.z+=dt*blowerPower*jet*(Math.cos(n*.91+time*11.7)*25-b.position.x*4)}}v.y-=gravity*dt;const maxSpeed=13;if(v.lengthSq()>maxSpeed*maxSpeed)v.setLength(maxSpeed);b.position.addScaledVector(v,dt);const len=b.position.length();if(len>3.05){const normal=b.position.clone().normalize();b.position.multiplyScalar(3.05/len);const normalSpeed=v.dot(normal);if(normalSpeed>0)v.addScaledVector(normal,-(1+restitution)*normalSpeed);if(normal.y<-.72){v.x*=Math.exp(-2.4*dt);v.z*=Math.exp(-2.4*dt);if(Math.abs(v.y)<.16)v.y=0}}v.multiplyScalar(Math.exp(-airDrag*dt));const roll=v.length()*dt/.27;b.rotation.x+=roll;b.rotation.z-=v.x*dt/.27});solveBallCollisions();if(extracting){const item=extracting,b=item.b;if(item.phase==='lift'){item.liftT=Math.min(item.liftT+dt/1.05,1);const rise=THREE.MathUtils.smoothstep(item.liftT,0,1)*6.25;lift.position.y=rise;b.position.set(0,-2.65+rise,.35);if(item.liftT>=1){item.phase='rail';lift.position.y=0;b.position.copy(item.railPath.getPointAt(0))}}else{const u=Math.min(item.railDistance/item.railLength,1),tangent=item.railPath.getTangentAt(u),slope=Math.max(.015,-tangent.y),gravityAlong=28*slope,rollingResistance=.22+item.railSpeed*.045;item.railSpeed=Math.max(.18,Math.min(11,item.railSpeed+(gravityAlong-rollingResistance)*dt));item.railDistance+=item.railSpeed*dt;const nextU=Math.min(item.railDistance/item.railLength,1);b.position.copy(item.railPath.getPointAt(nextU));const roll=item.railSpeed*dt/.27;b.rotation.x+=roll;b.rotation.z-=roll*.42;if(nextU>=1){b.position.copy(item.target);b.scale.setScalar(1.32);b.userData.collected=true;plates[item.index].material.map.dispose();plates[item.index].material.map=plateTexture(item.n,item.index);plates[item.index].material.needsUpdate=true;extracting=null;item.resolve()}}}machine.rotation.y=Math.sin(performance.now()*.00025)*.06;renderer.render(scene,camera);requestAnimationFrame(animate)}animate();
